
local Ruu = require "ruu2.ruu2"

local function getInput()
end

local function btn1Press(self, btn, ...)
	print("btn 1 pressed", self, btn)
end

function init(self)
	self.ruu = Ruu(self, getInput)
	msg.post(".", "acquire_input_focus")

	local btn = self.ruu:Button("button1", btn1Press):args("my argument", "arg2", 45.2398, "bye")
end

function on_input(self, action_id, action)
	self.ruu:input(action_id, action)
end
